AddCSLuaFile()

util.AddNetworkString( "ACE_KilledByACF" )
util.AddNetworkString( "ACE_RenderDamage" )
util.AddNetworkString( "ACE_Notify" )
util.AddNetworkString( "ACE_ArmorSummary" )
util.AddNetworkString( "ace_smokewind" )
util.AddNetworkString( "ACE_CamOverride" )
util.AddNetworkString( "ACE_DPStatus" )
util.AddNetworkString( "ACE_Scalable_Network" )
util.AddNetworkString( "ACE_SendMessage" )
util.AddNetworkString( "ACE_Wind" )
util.AddNetworkString( "ACE_Vignette" )
util.AddNetworkString( "ACE_SettingsSync" )
util.AddNetworkString( "ACE_HeatSettings" )
