"""Builds ACE Customs, an add-on that runs on top of ACE Canary, from this branch.

Every file the branch changes against the Canary commit it is built on (CANARY_BASE) must
be handled by one of the rules below, or the build stops:

  new files            shipped at their own path. Definition files in folders ACE's loader
                       scans move to lua/ace_customs/defs/ so they load after Customs'
                       definition functions exist.
  changed files        a copy goes to lua/ace_customs/override/<path>; the bootstrap
                       (customs/lua/autorun/acf_zz_ace_customs.lua) loads it after ACE.
                       Changed entities and weapons ship their whole folder.
  hand-patched files   ACE files whose changes customs/lua/ace_customs/patches/ re-creates by
                       hand. Their diff is fingerprinted; when it changes, the build stops
                       until the patch is checked and the fingerprint updated.
  E2 acf.lua           the added functions go to core/custom/acf_customs.lua (additions only).

Usage: python tools/customs/build_customs.py [--ref HEAD] [--out DIR] [--gma]
"""
import argparse
import hashlib
import os
import shutil
import subprocess
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CANARY_BASE = "ea401eaa3299c0e290d1a0f1a1c0be80d7c33470"
DEFAULT_OUT = r"E:\GMODDS\ace-customs-build\ace_customs"
GMAD = r"E:\Programs\Steam\steamapps\common\GarrysMod\bin\gmad.exe"

# Folders under lua/ace/shared/ that ACE's loader includes everything from.
LOADER_FOLDERS = {
    "armor", "guns", "rounds", "missiles", "mines", "radars", "ammocrates", "engines",
    "gearboxes", "guidances", "fueltanks", "fuses", "sounds", "tools", "crewseats",
    "extras", "explosives",
}

# Changed ACE files the bootstrap re-runs whole.
OVERRIDE_FILES = {
    "lua/ace/shared/sh_ace_functions.lua",
    "lua/ace/server/sv_heat.lua",
    "lua/ace/server/sv_adminsettings.lua",
    "lua/ace/client/cl_acemenu_gui.lua",
    "lua/starfall/libs_sv/acf.lua",
}
OVERRIDE_ENTITIES = {"acf_engine", "acf_gearbox", "acf_fueltank"}
OVERRIDE_WEAPONS = {"weapon_ace_torch"}
OVERRIDE_TOOLS = {"acemenu", "acesound"}

# Hand-patched ACE files (filled with the current diff fingerprint during the build).
HAND = {
    "lua/autorun/acf_globals.lua": None,
    "lua/ace/shared/sh_ace_loader.lua": None,
    "lua/ace/server/sv_acfbase.lua": None,
    "lua/ace/shared/sv_ace_networking.lua": None,
    "lua/ace/shared/fueltanks/basic.lua": None,
    "lua/ace/shared/ammocrates/ammocrates.lua": None,
}
HAND_FINGERPRINTS = {
    "lua/autorun/acf_globals.lua": "eb71739f05ea",               # patches/sh_globals.lua
    "lua/ace/shared/sh_ace_loader.lua": "6f4c29925f29",          # patches/sh_loader.lua
    "lua/ace/server/sv_acfbase.lua": "df4304fa3529",             # patches/sv_acfbase.lua
    "lua/ace/shared/sv_ace_networking.lua": "b2d7644e919e",      # patches/sh_globals.lua
    "lua/ace/shared/fueltanks/basic.lua": "a01a5f2e3a5e",        # patches/sh_loader.lua
    "lua/ace/shared/ammocrates/ammocrates.lua": "7a39c4b7162f",  # patches/sh_loader.lua
}

E2_SV = "lua/entities/gmod_wire_expression2/core/custom/acf.lua"
E2_CL = "lua/entities/gmod_wire_expression2/core/custom/cl_acf.lua"

SKIP_PREFIXES = ("tests/", "docs/", "tools/", "customs/", "lua/tests/", ".github/", ".claude/")
SKIP_SUFFIXES = (".md", ".py")
CONTENT_PREFIXES = ("models/", "materials/", "sound/", "resource/", "particles/")

E2_HEADER = """-- ACE Customs: E2 functions the mobility rework adds (generated by build_customs.py from the
-- branch's core/custom/acf.lua; loads after ACE's acf.lua).
E2Lib.RegisterExtension("acecustoms", true)

local validPhysics = E2Lib.validPhysics
local abs, round, clamp, floor, min, max = math.abs, math.Round, math.Clamp, math.floor, math.min, math.max
local pi = math.pi
local ACE = ACE

local function isEngine(ent)
	if not validPhysics(ent) then return false end
	return ent:GetClass() == "acf_engine"
end

local function isGearbox(ent)
	if not validPhysics(ent) then return false end
	return ent:GetClass() == "acf_gearbox"
end

local function restrictInfo(ply, ent)
	if not ACE.RestrictInfo then return false end

	return not ent:CPPICanTool(ply, "acfmenu")
end

__e2setcost(1)

do
"""


def git(*args, binary=False):
    out = subprocess.run(["git", "-C", REPO, *args], check=True, capture_output=True)
    return out.stdout if binary else out.stdout.decode("utf-8")


def diff_lines(ref, path):
    text = git("diff", "--ignore-cr-at-eol", "-U0", CANARY_BASE, ref, "--", path)
    lines = [l for l in text.splitlines() if not l.startswith(("+++", "---"))]
    return [l for l in lines if l.startswith(("+", "-"))]


def fingerprint(ref, path):
    return hashlib.sha1("\n".join(diff_lines(ref, path)).encode("utf-8")).hexdigest()[:12]


def write(out, rel, data):
    dest = os.path.join(out, *rel.split("/"))
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "wb") as f:
        f.write(data)


def show(ref, path):
    return git("show", f"{ref}:{path}", binary=True)


def ls_tree(ref, folder):
    return [p for p in git("ls-tree", "-r", "--name-only", ref, "--", folder).splitlines() if p]


def build(ref, out):
    errors = []
    changes = []
    for line in git("diff", "--name-status", "--no-renames", CANARY_BASE, ref).splitlines():
        status, path = line.split("\t", 1)
        if path.startswith(SKIP_PREFIXES) or path.endswith(SKIP_SUFFIXES) or path == "addon.json":
            continue
        changes.append((status, path))

    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(out)

    folders_done = set()
    counts = {"new": 0, "override": 0, "hand": 0, "content": 0}
    for status, path in changes:
        if path.startswith(CONTENT_PREFIXES):
            if status != "A":
                errors.append(f"{path}: changes ACE content ({status}); Customs can only add content")
                continue
            write(out, path, show(ref, path))
            counts["content"] += 1
            continue

        if not path.startswith("lua/"):
            errors.append(f"{path}: not handled ({status})")
            continue

        if status == "D":
            errors.append(f"{path}: deleted from ACE; Customs cannot remove ACE files")
            continue

        if status == "A":
            parts = path.split("/")
            if len(parts) == 5 and parts[1:3] == ["ace", "shared"] and parts[3] in LOADER_FOLDERS:
                write(out, f"lua/ace_customs/defs/{parts[3]}_{parts[4]}", show(ref, path))
            else:
                write(out, path, show(ref, path))
            counts["new"] += 1
            continue

        # Changed ACE files.
        if path in HAND:
            HAND[path] = fingerprint(ref, path)
            counts["hand"] += 1
            continue

        if path == E2_SV:
            removed = [l for l in diff_lines(ref, path) if l.startswith("-")]
            if removed:
                errors.append(f"{path}: the branch removes lines; acf_customs.lua only carries additions")
                continue
            added = [l[1:] for l in diff_lines(ref, path) if l.startswith("+")]
            body = E2_HEADER + "\n".join(added) + "\nend\n"
            write(out, path.replace("acf.lua", "acf_customs.lua"), body.encode("utf-8"))
            counts["override"] += 1
            continue

        if path == E2_CL:
            added = [l[1:] for l in diff_lines(ref, path) if l.startswith("+")]
            bad = [l for l in added if not l.startswith("E2Helper.Descriptions[")]
            if bad:
                errors.append(f"{path}: expected only E2Helper.Descriptions lines, got {bad[0]!r}")
                continue
            body = "-- ACE Customs: E2 helper text (generated by build_customs.py).\n" + "\n".join(added) + "\n"
            write(out, path.replace("cl_acf.lua", "cl_acf_customs.lua"), body.encode("utf-8"))
            counts["override"] += 1
            continue

        parts = path.split("/")
        folder = None
        if parts[1] == "entities" and parts[2] in OVERRIDE_ENTITIES:
            folder = "/".join(parts[:3])
        elif parts[1] == "weapons" and parts[2] in OVERRIDE_WEAPONS:
            folder = "/".join(parts[:3])
        if folder:
            if folder not in folders_done:
                folders_done.add(folder)
                for f in ls_tree(ref, folder):
                    write(out, "lua/ace_customs/override/" + f[4:], show(ref, f))
                    counts["override"] += 1
            continue

        overridable = (
            path in OVERRIDE_FILES
            or (path.startswith("lua/ace/shared/engines/") and path.count("/") == 4)
            or (path.startswith("lua/weapons/gmod_tool/stools/")
                and os.path.splitext(parts[-1])[0] in OVERRIDE_TOOLS)
        )
        if overridable:
            body = show(ref, path)
            # The menu tool builds its panel from the GUI file by path; point it at Customs' copy.
            if path == "lua/weapons/gmod_tool/stools/acemenu.lua":
                old, new = b'"ace/client/cl_acemenu_gui.lua"', b'"ace_customs/override/ace/client/cl_acemenu_gui.lua"'
                if old not in body:
                    errors.append(f"{path}: no vgui.RegisterFile of {old.decode()} to redirect")
                body = body.replace(old, new)
            write(out, "lua/ace_customs/override/" + path[4:], body)
            counts["override"] += 1
            continue

        errors.append(f"{path}: changed ACE file with no Customs rule (add it to OVERRIDE_* or HAND)")

    for path, fp in HAND.items():
        known = HAND_FINGERPRINTS.get(path)
        if fp is None:
            continue
        if known != fp:
            errors.append(f"{path}: diff fingerprint {fp} (patch written for {known}); check "
                          f"customs/lua/ace_customs/patches/ still matches the branch, then set "
                          f"HAND_FINGERPRINTS[{path!r}] = {fp!r}")

    # Hand-written Customs files (bootstrap, patches, addon.json).
    src = os.path.join(REPO, "customs")
    for root, _, files in os.walk(src):
        for name in files:
            full = os.path.join(root, name)
            rel = os.path.relpath(full, src).replace(os.sep, "/")
            with open(full, "rb") as f:
                write(out, rel, f.read())

    return errors, counts


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ref", default="HEAD", help="branch commit to build from (default HEAD)")
    ap.add_argument("--out", default=DEFAULT_OUT, help="output add-on folder")
    ap.add_argument("--gma", action="store_true", help="also pack it with gmad")
    args = ap.parse_args()

    errors, counts = build(args.ref, args.out)
    if errors:
        print("ACE Customs build failed:")
        for e in errors:
            print("  - " + e)
        return 1

    print(f"ACE Customs built in {args.out}: {counts['new']} new, {counts['override']} override, "
          f"{counts['hand']} hand-patched, {counts['content']} content files")

    if args.gma:
        gma = args.out.rstrip("\\/") + ".gma"
        subprocess.run([GMAD, "create", "-folder", args.out, "-out", gma, "-warninvalid"], check=True)
        print(f"Packed {gma} ({os.path.getsize(gma) / 1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
